import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

interface MetaTag {
  image: string;
  title: string;
}

const Home: NextPage = ({ meta }: any) => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@joeblau" />
        <meta name="twitter:title" content={meta.title} />
        <meta name="twitter:description" content="Shane test" />
        <meta name="twitter:image" content={meta.image} />

        <meta property="og:url" content={router.pathname} key="ogurl" />
        <meta property="og:image" content={meta.image} key="ogimage" />
        <meta property="og:site_name" content="" key="ogsitename" />
        <meta property="og:title" content={meta.title} key="ogtitle" />
        <meta property="og:description" content="Shane test" key="ogdesc" />
        <title>{meta.title}</title>
      </Head>

      <main className={styles.main}>Hello World</main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({
  query,
}: GetServerSidePropsContext) => {
  const { t } = query;
  const stringTitle = t == null ? "Test" : String(t);

  const meta: MetaTag = {
    image: `https://via.placeholder.com/1368x642/222/DDD.png?text=${stringTitle}`,
    title: stringTitle,
  };

  return {
    props: { meta }, // will be passed to the page component as props
  };
};

export default Home;
